/**
 * data.js — Shipment items dataset
 * Jabil AI Tariff Calculation Engine · Use Case 2
 * Batch #TCA-2026-0518 · MY→US Export Lane
 */

const ITEMS = [
  {
    id: '01',
    hs: '8534.00.1000',
    name: 'PCB Assembly, 4-layer, SMT',
    origin: 'MY',
    conf: 98,
    duty: 0,
    fta: 'CPTPP',
    status: 'approved',
    shipmentValue: 42000,
    description: 'Standard 4-layer surface-mount printed circuit board assembly for industrial controllers.',
    cooCertified: true,
    rvContent: 62,
  },
  {
    id: '02',
    hs: '8542.31.0000',
    name: 'Integrated Circuit, LQFP-64',
    origin: 'MY',
    conf: 96,
    duty: 2240,
    fta: 'CPTPP',
    status: 'approved',
    shipmentValue: 56000,
    description: 'LQFP-64 packaged microcontroller, 32-bit ARM Cortex-M4 core.',
    cooCertified: true,
    rvContent: 55,
  },
  {
    id: '03',
    hs: '8471.49.0000',
    name: 'Embedded Computing Module, x86',
    origin: 'MY',
    conf: 94,
    duty: 0,
    fta: 'CPTPP',
    status: 'approved',
    shipmentValue: 98000,
    description: 'COM Express Type 6 module with Intel Atom x6000E series processor.',
    cooCertified: true,
    rvContent: 48,
  },
  {
    id: '04',
    hs: '8516.90.9000',
    name: 'Heating Element Assembly',
    origin: 'CN',
    conf: 91,
    duty: 4890,
    fta: 'MFN',
    status: 'approved',
    shipmentValue: 97800,
    description: 'Resistive heating element with thermal fuse, for industrial ovens.',
    cooCertified: true,
    rvContent: 0,
  },
  {
    id: '05',
    hs: '8536.90.9000',
    name: 'Connector Housing, 24-pin, IP67',
    origin: 'MY',
    conf: 97,
    duty: 0,
    fta: 'CPTPP',
    status: 'approved',
    shipmentValue: 24500,
    description: 'IP67-rated 24-pin connector housing for automotive applications.',
    cooCertified: true,
    rvContent: 71,
  },
  {
    id: '06',
    hs: '8501.10.9000',
    name: 'DC Motor, 12V Brushless',
    origin: 'MY',
    conf: 89,
    duty: 1120,
    fta: 'ATIGA',
    status: 'pending',
    shipmentValue: 44800,
    description: 'Brushless DC motor, 12V, 5W, hall-sensor feedback, for robotics.',
    cooCertified: true,
    rvContent: 42,
  },
  {
    id: '07',
    hs: '8544.42.9000',
    name: 'USB-C Cable Assembly, 240W',
    origin: 'MY',
    conf: 95,
    duty: 0,
    fta: 'CPTPP',
    status: 'approved',
    shipmentValue: 18600,
    description: 'USB-C 2.1 cable assembly, 240W EPR power delivery, 2m.',
    cooCertified: true,
    rvContent: 58,
  },
  {
    id: '08',
    hs: '8479.89.9000',
    name: 'Pneumatic Valve Actuator',
    origin: 'DE',
    conf: 86,
    duty: 5600,
    fta: 'MFN',
    status: 'pending',
    shipmentValue: 112000,
    description: 'Double-acting pneumatic valve actuator, ISO 5211 flange, stainless steel.',
    cooCertified: true,
    rvContent: 0,
  },
  {
    id: '09',
    hs: '8541.10.0000',
    name: 'Rectifier Diode, 1A, SMD',
    origin: 'MY',
    conf: 99,
    duty: 0,
    fta: 'CPTPP',
    status: 'approved',
    shipmentValue: 8200,
    description: 'Surface-mount silicon rectifier diode, 1A 1000V, SMA package.',
    cooCertified: true,
    rvContent: 65,
  },
  {
    id: '10',
    hs: '8525.80.1000',
    name: 'CMOS Image Sensor Module',
    origin: 'JP',
    conf: 93,
    duty: 3280,
    fta: 'MJCEPA',
    status: 'approved',
    shipmentValue: 82000,
    description: '20MP CMOS image sensor module with M12 lens mount, for machine vision.',
    cooCertified: true,
    rvContent: 0,
  },
  {
    id: '11',
    hs: '8542.31.0000',
    name: 'Multi-chip Module, BGA-256',
    origin: 'MY',
    conf: 82,
    duty: 0,
    fta: 'CPTPP',
    status: 'pending',
    shipmentValue: 124000,
    description: 'Multi-chip module in BGA-256 package, integrating processor and memory dies.',
    cooCertified: true,
    rvContent: 44,
  },
  {
    id: '12',
    hs: '8518.40.0000',
    name: 'Audio Amplifier Board, 2×50W',
    origin: 'MY',
    conf: 97,
    duty: 0,
    fta: 'CPTPP',
    status: 'approved',
    shipmentValue: 31200,
    description: 'Class-D stereo amplifier board, 2×50W, I²C control interface.',
    cooCertified: true,
    rvContent: 60,
  },
  {
    id: '13',
    hs: '8504.40.1000',
    name: 'AC-DC Power Supply, 500W',
    origin: 'MY',
    conf: 95,
    duty: 0,
    fta: 'CPTPP',
    status: 'approved',
    shipmentValue: 67500,
    description: '500W enclosed AC-DC switching power supply, 24VDC output, UL approved.',
    cooCertified: true,
    rvContent: 52,
  },
  {
    id: '14',
    hs: '8534.00.9000',
    name: 'PCB Assembly, 32-layer, BGA',
    origin: 'MY',
    conf: 78,
    duty: 0,
    fta: 'CPTPP',
    status: 'flagged',
    shipmentValue: 148200,
    description: '32-layer high-density PCB assembly with BGA-1156 package components.',
    cooCertified: true,
    rvContent: 41,
    flagReason: 'BGA packaging ambiguity — may classify as 8542 (IC) vs 8534 (PCB).',
  },
  {
    id: '15',
    hs: '8473.30.0000',
    name: 'DRAM Memory Module, DDR5',
    origin: 'KR',
    conf: 99,
    duty: 0,
    fta: 'MKFTA',
    status: 'approved',
    shipmentValue: 88400,
    description: '32GB DDR5-4800 ECC registered DIMM, server-grade.',
    cooCertified: true,
    rvContent: 0,
  },
];
